
import { NextResponse } from 'next/server';
import https from 'https';
import fs from 'fs';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';
import crypto from 'crypto';

export async function POST(request: Request) {
  try {
    const requestURL = new URL(request.url);
    const { amount, message } = await request.json();

    const instructionUUID = uuidv4().replace(/-/g, '').toUpperCase();
    
    const callbackUrl = `https://${requestURL.host}/api/callback?id=${instructionUUID}`;

    const payload = {
      payoutInstructionUUID: instructionUUID,
      payerPaymentReference: '0123456789',
      signingCertificateSerialNumber: '4F24C03A0295A0B53596240EA8C0F430',
      payerAlias: '1231181189',
      payeeAlias: '46768648198',
      payeeSSN: '196210123235',
      amount,
      currency: 'SEK',
      payoutType: 'PAYOUT',
      message,
      instructionDate: new Date().toISOString(),
    };

    // The payload needs to be signed. The https.Agent with pfx is for client certificate authentication, not for signing the payload.
    // The signature is a Base64 encoded signature of the payload, generated by hashing the payload with SHA-512 and then signing it with the private key of the signing certificate.
    // The Swish API expects a body like { "payload": <the payload object>, "signature": "...", "callbackUrl": "..." }
    const pfxPath = path.resolve(process.cwd(), 'mss_client_cert/Swish_Merchant_TestSigningCertificate_1234679304.p12');
    const privateKeyPath = path.resolve(process.cwd(), 'mss_client_cert/Swish_Merchant_TestSigningCertificate_1234679304.key');
    const privateKey = fs.readFileSync(privateKeyPath);

    const createHmacSha512 = (payload: any, privateKey: string | Buffer) => {
      const hmac = crypto.createHmac('sha512', privateKey);
      hmac.update(JSON.stringify(payload));
      return hmac.digest('base64');
    };

    const signature = createHmacSha512(payload, privateKey);

    const requestBody = {
      payload,
      signature,
      callbackUrl,
    };

    const pfx = fs.readFileSync(pfxPath);

    const agent = new https.Agent({
      pfx,
      passphrase: 'swish',
    });

    const options = {
      hostname: 'mss.cpc.getswish.net',
      port: 443,
      path: '/swish-cpcapi/api/v1/payouts/',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      agent,
    };

    const swishRequest = new Promise((resolve, reject) => {
      const req = https.request(options, (res) => {
        let data = '';
        res.on('data', (chunk) => {
          data += chunk;
        });
        res.on('end', () => {
          if (res.statusCode && res.statusCode >= 200 && res.statusCode < 300) {
            resolve({ statusCode: res.statusCode, data });
          } else {
            reject(new Error(`Request failed with status code ${res.statusCode}: ${data}`));
          }
        });
      });

      req.on('error', (error) => {
        reject(error);
      });

      req.write(JSON.stringify(requestBody));
      req.end();
    });

    const result = await swishRequest;

    return NextResponse.json(result);
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: 'Something went wrong' }, { status: 500 });
  }
}
